spring:
  application:
    name: games-portal

server:
  port: 0

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

info:
  author:
    name: Gabriel
    email: example@email.com