spring:
  application:
    name: games-portal
  data:
    rest:
      base-path: /data-api

server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      force: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

info:
  author:
    name: Gabriel
    email: example@email.com