server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:schema_game.sql
      data-locations: classpath:data_game.sql
